### ISSUE TITLE
View-k és Layout-ok

### ISSUE THREAD

**Issue by kanyokristof95** [kanyokristof95/Running-Tracker#10]
A különböző view-k és layout-k, illetve az új oldal betöltését bemutató példa projekt.

**Comment by antalist** [comment]
A mintaprogramot feltettem [ide](https://github.com/kanyokristof95/Running-Tracker/tree/master/Examples/View).

Van benne példa egy **ListView** bemutatására, ami hasznos lehet a [futások listázásánál](https://github.com/kanyokristof95/Running-Tracker/blob/master/Documentation/Mockup/Export/HistoryActivity-1.png). Az egyes listaelemekre kattintva, vagy hosszan kattintva más oldalakra irányít át.

Szerepel benne példa egy összetettebb nézettel rendelkező oldal elkészítésére (**LinearLayout**-ok segítségével), ami hasonlít a [futás közben látható képernyőre](https://github.com/kanyokristof95/Running-Tracker/blob/master/Documentation/Mockup/Export/MainActivity.png) (a tervezett drótvázterv alapján).

Továbbá még egyszerűbb, oldalak közti navigációt mutat be.
