### ISSUE TITLE
A mozdulat meghatározása

### ISSUE THREAD

**Issue by kanyokristof95** [kanyokristof95/Running-Tracker#13]
Egy példa alkalmazás elkészítése, amely képes arra, hogy felismerje, hogy az illetőnél sétál vagy fut.

**Comment by faudori** [comment]
https://developers.google.com/android/reference/com/google/android/gms/location/ActivityRecognition?utm_source=gdev-yt&utm_medium=video&utm_term=&utm_content=activityrec&utm_campaign=100days

**Comment by kanyokristof95** [comment]
Az alkalmazás jelenlegi verziója nem támogatja a különböző mozgások megkülönböztetését.
