### ISSUE TITLE
xamarin.forms vs xamarin.android

### ISSUE THREAD

**Issue by kanyokristof95** [kanyokristof95/Running-Tracker#4]
Melyik legyen: xamarin.forms vs xamarin.android?

Én úgy tapasztaltam, hogy sokkal egyszerűbben ki tudjuk használni az android funkcióit a xamarin.android-on keresztül.

**Comment by kanyokristof95** [comment]
A **Xamarin Player** nem mindig működik jól, gyakran megszakad a kapcsolat a telefon és a Visual Studio esetén, illetve néha nagyon nehezen lehet csak szinkronizálni. Ráadásul xamarin.android esetén nem is működik, mivel _native_ esetben nem használható.

Én ettől függetlenül továbbra is a xamarin.android-ot ajánlom, mivel [USB kábel segítségével](https://github.com/kanyokristof95/Running-Tracker/wiki/Technikai-be%C3%A1ll%C3%ADt%C3%A1sok#alkalmaz%C3%A1s-android-on-val%C3%B3-futtat%C3%A1sa) könnyen futtatható közvetlenül a telefonon, ráadásul a debugolás is egyszerűbb.

**Comment by antalist** [comment]
Én is a xamarin.android-ot támogatom.

**Comment by faudori** [comment]
Nekem is jó a xamarin.android

**Comment by kanyokristof95** [comment]
Rendben, akkor a **xamarin.android** győzött!
